config/routes.rb
Rails.application.routes.draw do
  get 'reports/all_data'

  root 'reports#all_data'
  resources :reports do
   collection do
     get 'hits_for'
     get 'search'
     post 'search'
   end
 end

end

app/models/assembly.rb
class Assembly < ActiveRecord::Base
  has_many :sequences
end

app/models/gene.rb
class Gene < ActiveRecord::Base
  belongs_to :sequence
  has_many :hits, as: :subject

  validates :sequence_id, presence: true
end

app/models/hit.rb
require 'csv'

class Hit < ActiveRecord::Base
  belongs_to :subject, polymorphic: true

  validates :subject_id, presence: true
  validates :subject_type, presence: true

  def self.export(count)
    CSV.open("tmp/data.csv", "wb") do |csv|
      csv << ["Assembly Name",
          "Assembly Date",
          "Sequence",
          "Sequence Quality",
          "Gene Sequence",
          "Gene Starting Position",
          "Gene Direction",
          "Hit Name",
          "Hit Sequence",
          "Hit Similarity"]
      Hit.limit(count).each do |h|
        csv << [h.subject.sequence.assembly.name,
            h.subject.sequence.assembly.name,
            h.subject.sequence.dna,
            h.subject.sequence.quality,
            h.subject.dna,
            h.subject.starting_position,
            h.subject.direction,
            h.match_gene_name,
            h.match_gene_dna,
            h.percent_similarity]
      end
    end
  end
end

app/models/sequence.rb
class Sequence < ActiveRecord::Base
  belongs_to :assembly
  has_many :genes

  validates :assembly_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  helper_method :memory_in_mb

#
#




  def all_data
    @start_time = Time.now

    @sequences = []
    @genes = []
    @hits = []
    @assembly = Assembly.find_by_name(params[:name])
    @assembly.sequences.each do |s|
      @sequences << s
      s.genes.each do |g|
        @genes << g
        g.hits.each do |h|
          @hits << h
        end
      end
    end
    @hits.sort! {|a, b| b.percent_similarity <=> a.percent_similarity}

    @memory_used = memory_in_mb
  end

  def search
     if params[:search]
     results = []
       q = "%#{params[:search]}%"
       @assembly = Hit.joins(:subject).where("genes LIKE ? OR sequences.dna LIKE ? OR asseblies.name LIKE ?",q ,q ,q)
     end
   end

  private def memory_in_mb
    `ps -o rss -p #{$$}`.strip.split.last.to_i / 1024
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DatabaseOptimizations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/all_data.html.erb
<h1>Hits for <%= @assembly.name %></h1>
<p>Total time before HTML is generated: <%= Time.now - @start_time %> s</p>
<p>Memory used before HTML is generated: <%= @memory_used %> MB</p>
<p>Number of hits: <%= @hits.length %></p>

<table>
  <thead>
    <tr>
      <th>Matching Gene Name</th>
      <th>Matching DNA</th>
      <th>Percent Similarity</th>
    </tr>
  </thead>
  <tbody>
    <% @hits.each do |h| %>
      <tr>
        <td><%= h.match_gene_name %></td>
        <td><%= h.match_gene_dna.first(100) %></td>
        <td><%= h.percent_similarity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>Total time before HTML is generated: <%= Time.now - @start_time %> s</p>
<p>Memory used after HTML is generated: <%= memory_in_mb %> MB</p>

app/views/reports/search.html.erb
<h1>Search All Reports</h1>
<%= form_tag search_reports_path, method: :get do %>
  <%= text_field_tag :search  %>
  <%= submit_tag "Search" %>
<% end %>

<p> Please enter the terms you want to search for! <p>

  <h1>Hits for <%= @assembly.name %></h1>

  <table>
    <thead>
      <tr>
        <th>Matching Gene Name</th>
        <th>Matching DNA</th>
        <th>Percent Similarity</th>
      </tr>
    </thead>
    <tbody>
      <% @hits.each do |h| %>
        <tr>
          <td><%= h.match_gene_name %></td>
          <td><%= h.match_gene_dna.first(100) %></td>
          <td><%= h.percent_similarity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>